version: 1.5.{build}
os: Visual Studio 2015
clone_folder: C:\projects\pyIbex
test: off
configuration:
    - Release
    # - Debug
build:
    parallel: true
# branches:
  # only:
    # - master

environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
    DL_IBEX_FILES_WIN32: "https://github.com/benEnsta/ibex-lib/releases/download/ibex-lib-2.8.6dev1/ibex-lib-2.8.6-win32.zip"
    DL_IBEX_FILES_WIN64: "https://github.com/benEnsta/ibex-lib/releases/download/ibex-lib-2.8.6dev1/ibex-lib-2.8.6-win64.zip"
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON_DIR: "C:\\Python34"
      PYTHON_EXE: "C:\\Python34/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN32%"
      IBEX_FILES: "ibex-lib-2.8.6-win32"
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON_DIR: "C:\\Python35"
      PYTHON_EXE: "C:\\Python35/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN32%"
      IBEX_FILES: "ibex-lib-2.8.6-win32"
    - CMAKE_PLATFORM: "Visual Studio 14 2015"
      PYTHON_DIR: "C:\\Python36"
      PYTHON_EXE: "C:\\Python36/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN32%"
      IBEX_FILES: "ibex-lib-2.8.6-win32"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python34-x64"
      PYTHON_EXE: "C:\\Python34-x64/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN64%"
      IBEX_FILES: "ibex-lib-2.8.6-win64"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python35-x64"
      PYTHON_EXE: "C:\\Python35-x64/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN64%"
      IBEX_FILES: "ibex-lib-2.8.6-win64"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python36-x64"
      PYTHON_EXE: "C:\\Python36-x64/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN64%"
      IBEX_FILES: "ibex-lib-2.8.6-win64"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python37-x64"
      PYTHON_EXE: "C:\\Python37-x64/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN64%"
      IBEX_FILES: "ibex-lib-2.8.6-win64"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python38-x64"
      PYTHON_EXE: "C:\\Python38-x64/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN64%"
      IBEX_FILES: "ibex-lib-2.8.6-win64"
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python38-x64"
      PYTHON_EXE: "C:\\Python38-x64/python.exe"
      DL_IBEX_FILES: "%DL_IBEX_FILES_WIN64%"
      IBEX_FILES: "ibex-lib-2.8.6-win64"

  USERNAME:
    secure: x/KrtKQDdjxKhvPlvfdiMQ==
  PASWORD:
    secure: C5uWvbl1OHCVoprbRYTGD7LLzuUMtj18MtxytCqLmh8=
  FTP_PASSWD:
    secure: U58Tazcrcj6n+oP1CxfRCQ==

install:
  - cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
  - cmd: "%PYTHON_EXE% -m pip install --disable-pip-version-check --user --upgrade pip wheel"
  - ps: >-

      (new-object net.webclient).DownloadFile($env:DL_IBEX_FILES, 'C:\projects\pyIbex\ibex-lib.zip')
      
      ls C:\projects\pyIbex

      cd C:\projects\pyIbex

      7z x -tzip -oC:"ibex-lib" "C:\projects\pyIbex\ibex-lib.zip"

      ls C:\projects\pyIbex\ibex-lib

  - cmd: "%PYTHON_DIR%/python.exe -m pip install vibes"

artifacts:
  - path: '**\*.whl'
    name: pip_wheel

build_script:
  - echo Running cmake..  .
  - cd c:\projects\pyIbex
  - git submodule init
  - git submodule update
  # - git clone -b build_process https://github.com/benEnsta/ibex-robotics.git ibex-robotics
  - mkdir build && cd build
  - cmake -G "%CMAKE_PLATFORM%"  -DPYBIND11_CPP_STANDARD=/std:c++14 -DPYTHON_EXECUTABLE:FILEPATH=%PYTHON_DIR%/python.exe -DCMAKE_PREFIX_PATH=C:\projects\pyIbex\ibex-lib\%IBEX_FILES%\share\ibex\cmake ..
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  # - set MSBuildOptions=/v:m /p:Configuration=%Configuration% /logger:%MSBuildLogger%
  # - msbuild %MSBuildOptions% INSTALL.vcxproj
  - cmake --build . --config %Configuration% -- /m /v:m
  - ctest -C %Configuration% -VV
  - msbuild %MSBuildOptions% src/pip_package.vcxproj


# deploy:
#   provider: FTP
#   protocol: ftps
#   host: bdesroch.privatedns.org
#   username: git
#   password:
#     secure: U58Tazcrcj6n+oP1CxfRCQ==
#   folder: gittmp/win
#   artifact: pip_wheel

deploy:
  release: pyibex-1.9.0
  description: 'pyIbex windows build'
  provider: GitHub
  auth_token:
    secure: Bu9kqyFD6errPkHu23iueJXI5x7JZ/8ZHVwoYNB1ZijEQ7KOySfC/sJ0fKBDgFOA
  folder: gittmp/win
  artifact: pip_wheel
  draft: true
  prerelease: false
  on:
  #   branch: with_cmake      # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
