# -*- coding: utf-8 -*-
""" doxygen2docstring.py

  This script converts XML file generated by Doxygen (C++)
  into docstring format (Python). The output is a C++ file
  containing char* strings of docstring values, available as
  constants. They can be used with pybind11 for sharing C++
  documentation to Python binding.
  
  Project: codac
  Author: Simon Rohou
  Date: 2020
"""

import os
import sys
import re
import xml.etree.ElementTree as ET

def normalize_template_label(str_template_label):

  return str_template_label \
    .replace("< ", "_") \
    .replace("<", "_") \
    .replace(", ", "") \
    .replace(",", "") \
    .replace(" >", "") \
    .replace(">", "")

# Turns the definition text of a declaration into the name of the macro that
# will carry its docstring. That text comes from doxygen, so anything doxygen
# words differently from one version to the next has to be removed here, or the
# macro ends up named differently depending on which doxygen ran and the
# bindings that spell the name out no longer compile. "typedef" is one of those:
# older doxygen writes the definition of an alias as "using X = typedef Y"
# where newer ones write "using X = Y", which is what gave
# USING_AFFINEMAINMATRIX_EQ_TYPEDEF_EIGEN_MATRIX_... on the CentOS manylinux
# images of .github/workflows/dockercentos.yml against the
# USING_AFFINEMAINMATRIX_EQ_EIGEN_MATRIX_... expected by
# python/src/core/domains/affine/codac2_py_AffineMatrix.cpp.
def normalize_label(str_label):

  # Runs of whitespace are collapsed first, because the text below turns every
  # space into an underscore and doxygen does not word its definitions the same
  # way from one version to the next: 1.15.0 renders the definition of an alias
  # with one space more than 1.17.0 does, which alone renamed
  # USING_AFFINEMAINMATRIX_EQ_EIGEN_MATRIX_... into
  # USING_AFFINEMAINMATRIX_EQ__EIGEN_MATRIX_... and stopped the bindings from
  # compiling on Ubuntu 26.04. Collapsing the underscores afterwards would not
  # do: plenty of macro names hold a legitimate double underscore, from a
  # trailing underscore in an identifier followed by _REF or _CONST
  # (NODEVALUE__REF and its like), and squeezing those would rename them all.
  str_label = re.sub(r'\s+', ' ', str_label)

  str_label = str_label \
    .replace("or<<", "OROUT") \
    .replace("or>>", "ORIN")

  return normalize_template_label(str_label) \
    .replace("constexpr ", "") \
    .replace("typedef ", "") \
    .replace("codac::", "") \
    .replace("codac2::", "") \
    .replace("std::", "") \
    .replace("const ", "const_") \
    .replace(" ", "_") \
    .replace("::", "_") \
    .replace("\"\"_", "LITT") \
    .replace("~", "TILD_") \
    .replace("operator+", "OPERATORPLUS") \
    .replace("operator-", "OPERATORMINUS") \
    .replace("operator*", "OPERATORMUL") \
    .replace("operator/", "OPERATORDIV") \
    .replace("operator[]", "OPERATORCOMPO") \
    .replace("operator()", "OPERATORCALL") \
    .replace("operator&=", "OPERATORINTEREQ") \
    .replace("operator|=", "OPERATORUNIONEQ") \
    .replace("operator&&", "OPERATORAND") \
    .replace("operator&", "OPERATORINTER") \
    .replace("operator||", "OPERATOROR") \
    .replace("operator|", "OPERATORUNION") \
    .replace("operator==", "OPERATOREQ") \
    .replace("operator!=", "OPERATORNEQ") \
    .replace("operator=", "OPERATORAFF") \
    .replace("operator!", "OPERATORNOT") \
    .replace("operator^", "OPERATORHAT") \
    .replace("&", "_REF") \
    .replace("*", "_PTR") \
    .replace("=", "EQ") \
    .replace("size_t", "SIZET") \
    .replace("...", "_VARIADIC") \
    .replace("(", "_") \
    .replace(")", "_") \
    .replace("__REF", "_REF") \
    .replace("__PTR", "_PTR") \
    .replace("-1", "MINUSONE")

def docstring_varname(memberdef, prefix=''):

  txt = prefix + normalize_label(memberdef.find(".//definition").text)

  for param in memberdef.findall("param"):
    if param.find("type") != None:
      txt += "_" + normalize_label("".join(param.find("type").itertext()))

  if memberdef.get('const') != None and memberdef.attrib['const'] == "yes":
    txt += "_const"

  if memberdef.get('static') != None and memberdef.attrib['static'] == "yes" and ("static_" not in txt):
    txt = "static_" + txt

  return txt.upper()


def get_originate_file(m):

    location_file = m.find(".//location").get("file").split("/")[-1]
    location_stem = os.path.splitext(location_file)[0]
    return (location_stem + "_docs.h").replace("codac2_", "codac2_py_")


if not os.path.exists(sys.argv[1]):
  print("-- /!\\ Enable to build doc files (generate XML Doxygen files first)")
  quit()

files = os.listdir(sys.argv[1])
for xml_doc in files:

  #if "_impl." in xml_doc: 
  #  continue

  # Parsing XML file from Doxygen output (XML mode enabled)
  tree = ET.parse(sys.argv[1] + "/" + xml_doc)
  root = tree.getroot()


  # Main documentation (ex: comment of the class)

  class_compound = root.find("./compounddef")

  if class_compound == None or (class_compound.get('kind') != None and \
    class_compound.attrib['kind'] == "dir"):
    continue

  class_name = class_compound.find("./compoundname").text

  if class_compound.attrib['kind'] != "file":

    with open(sys.argv[2] + "/" + get_originate_file(class_compound), 'a', encoding='utf-8') as f:

      print("/// Class " + class_name, file=f)
      #print("const char* "
      #   + normalize_label(class_name + "_MAIN").upper()
      #   + " = R\"Docstring documentation will be available in next release.\";", file=f)
      print("#define "
         + normalize_label(class_name + "_MAIN").upper()
         + " \"Docstring documentation will be available in next release.\"", file=f)


  # Members documentation (ex: methods, functions, etc.)

  prefix = ""
  if class_compound.attrib['kind'] == "file":
    prefix = class_name.replace(".h", "").replace("codac2_", "") + "_"

  for memberdef in root.findall(".//memberdef"):

    with open(sys.argv[2] + "/" + get_originate_file(memberdef), 'a', encoding='utf-8') as f:

      if memberdef.find("./definition") == None:
        continue

      # Doc string
      print("// " + memberdef.find("./definition").text, end="", file=f)
      argstring = memberdef.find("./argsstring").text
      if argstring:
        print(argstring, end="", file=f)
      print("", file=f)

      #if memberdef.get('id') != None and (memberdef.attrib['id'] == "codac2___interval__operations_8h_1a64ecd476860d3067b13595c4b3022edd" or memberdef.attrib['id'] == "classcodasc2_1_1_interval_matrix_template___1a8b52d938a0484425639aa86603b03009"):
      #  print("start")
      #  print("const char* " + docstring_varname(memberdef) + " = \"Docstring documentation will be available in next release.\"")
      #  exit(1)

      if memberdef.get('kind') != None and memberdef.attrib['kind'] == "friend" \
          and memberdef.get('inline') != None and memberdef.attrib['inline'] != "yes":
        print("// Friend member is not documented here.\n", file=f)
        continue

      #print("const char* "
      #   + docstring_varname(memberdef)
      #   + " = R\"Docstring documentation will be available in next release.\";", file=f)

      print("#define "
         + docstring_varname(memberdef, prefix)
         + " \"Docstring documentation will be available in next release.\"", file=f)

      print("\n", file=f)